<a href="https://colab.research.google.com/github/ahamedalshafath/assignment-task-1/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.version.version)
print(np.show_config())

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
a.size
a.itemsize
print('%d bytes'% (a.size * a.itemsize))

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
b=np.zeros(10)
b[4]=1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
b=np.arange(10,49)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
b=np.arange(10,49)
print(b[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
b=np.arange(0,9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
a=np.array([1,2,0,0,4,0])
b=a.nonzero()
b

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
a=np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
a=np.random.random((3,3,3))
a

array([[[0.21737599, 0.12309891, 0.03668601],
        [0.4081896 , 0.88010813, 0.96707189],
        [0.81233511, 0.66573497, 0.73014614]],

       [[0.78354095, 0.74016208, 0.45564068],
        [0.95697992, 0.49976682, 0.07741374],
        [0.8348502 , 0.27867468, 0.12915845]],

       [[0.06449697, 0.4089124 , 0.97650385],
        [0.8590532 , 0.53396035, 0.04501853],
        [0.02310294, 0.52583014, 0.22532293]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
a=np.random.random((10,10))
print(a.min())
print(a.max())

0.015793012553975472
0.9686280895231613


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
a=np.arange(30)
a.mean()

14.5

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
a=np.ones(30).reshape(6,5)
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
a=np.arange(1,13).reshape(3,4)
b=np.pad(a,pad_width=1,mode="constant",constant_values=0)
b

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  0],
       [ 0,  5,  6,  7,  8,  0],
       [ 0,  9, 10, 11, 12,  0],
       [ 0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
0*np.nan,np.nan==np.nan,np.inf>np.nan,np.nan-np.nan,0.3==3*0.1

(nan, False, False, nan, False)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
c=np.eye(5,5)
d=np.diag([1,2,3,4])
d=np.insert(d,4,np.zeros(d.shape[1]),axis=1)
d=np.insert(d,0,np.zeros(c.shape[0]),axis=0)
c+d


array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 2., 1., 0., 0.],
       [0., 0., 3., 1., 0.],
       [0., 0., 0., 4., 1.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
c=np.zeros(64).reshape(8,8)
c[::2,::2]=1
c[1:2,1:2]=1
c

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
a=np.arange(336).reshape(6,7,8)
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
a=np.tile(np.array([[1,0],[0,1]]),[4,4])
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
ab=np.random.random((5,5))
min,max=ab.min(),ab.max()
ab=(ab-min)/(max-min)
ab

array([[0.28261625, 0.4069979 , 0.84845344, 0.        , 1.        ],
       [0.99525879, 0.25689395, 0.53555145, 0.60177144, 0.08344242],
       [0.73063469, 0.87891227, 0.05590722, 0.4330204 , 0.35357747],
       [0.31639944, 0.07897729, 0.40336269, 0.32632668, 0.21320532],
       [0.24479955, 0.54551637, 0.885812  , 0.44458442, 0.71187214]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r",np.ubyte,1),
                  ("g",np.ubyte,1),
                  ("b",np.ubyte,1),
                  ("a",np.ubyte,1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
matr1=np.random.randint(2,10,(5,3))
matr2=np.random.randint(2,10,(3,2))
a=np.dot(matr1,matr2)
a

array([[ 62,  55],
       [ 85,  83],
       [ 85,  84],
       [108, 100],
       [ 47,  45]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
a=np.arange(15)
a[(a>3) & (a<=8)]*=-1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z=np.arange(12).reshape(3,4)
print(z)
print(z**z)
print(z<-z)
print(1j*z)
print(z/1/1)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[           1            1            4           27]
 [         256         3125        46656       823543]
 [    16777216    387420489  10000000000 285311670611]]
[[False False False False]
 [False False False False]
 [False False False False]]
[[0. +0.j 0. +1.j 0. +2.j 0. +3.j]
 [0. +4.j 0. +5.j 0. +6.j 0. +7.j]
 [0. +8.j 0. +9.j 0.+10.j 0.+11.j]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
a=np.random.uniform(-10,+10,10)
np.copysign(np.ceil(np.abs(a)),a)

array([ 4.,  4., -7.,  7., -1., -2., -5.,  4.,  5., -2.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x=np.arange(0,12)
y=np.arange(8,15)
z=np.intersect1d(x,y)
z

array([ 8,  9, 10, 11])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
np.seterr(all='ignore')
a=np.arange(3)/0
with np.errstate(divide='warn'):
        a=np.arange(3)/0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1)==np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
today=np.datetime64('today','D')
print('today:',today)
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
print('yesterday:',yesterday)
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print('tomorrow:',tomorrow)

today: 2022-11-21
yesterday: 2022-11-20
tomorrow: 2022-11-22


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
a=np.arange('2016-07','2016-08',dtype='datetime64[D]')
a

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
a=np.ones(5)
b=np.ones(5)
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(b,a,out=a)

array([-1., -1., -1., -1., -1.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
a=np.random.uniform(0,12,10)
print(a)
print(a-(a%1))
print(np.floor(a))
print(np.ceil(a)-1)
print(a.astype(int))
print(np.trunc(a))

[ 3.7043127   9.74672568  8.10984816  9.41418288  8.70496138 11.70973823
  2.33680007  2.36221166  6.91705657  9.95168815]
[ 3.  9.  8.  9.  8. 11.  2.  2.  6.  9.]
[ 3.  9.  8.  9.  8. 11.  2.  2.  6.  9.]
[ 3.  9.  8.  9.  8. 11.  2.  2.  6.  9.]
[ 3  9  8  9  8 11  2  2  6  9]
[ 3.  9.  8.  9.  8. 11.  2.  2.  6.  9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
a=np.zeros((5,5))
a+=np.arange(0,5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
  for x in range(10):
    yield x
z= np.fromiter(generate(),dtype=int,count=-1)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
a=np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x=np.random.randint(11,80,10)
print(x)
np.sort(x)

[57 45 32 31 18 17 34 29 56 49]


array([17, 18, 29, 31, 32, 34, 45, 49, 56, 57])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
import time 
begin_time=time.time()
x=np.arange(1000000)
np.sum(x)
end_time=time.time()
print(str(1000*(end_time-begin_time)))

begin_time2=time.time()
x=np.arange(1000000)
np.add.reduce(x)
end_time2=time.time()
print(str(1000*(end_time2-begin_time2)))


7.498502731323242
9.338617324829102


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
x=np.random.randint(0,2,5)
y=np.random.randint(0,2,5)
z=np.array_equal(x,y)
print(z)
z=np.allclose(x,y)
print(z)


False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
z=np.random.random((10,2))
x,y=z[:,0],z[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)


[1.13247018 0.78719047 0.76792212 0.18226254 0.71040788 0.7492306
 0.16976415 0.93384559 0.36503816 0.86843022]
[0.61577443 0.31823403 1.46634829 0.41124076 0.40214208 0.59199356
 0.65172849 0.97379198 1.41726393 0.56165286]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
x=np.random.random(10)
print(x)
t=np.argmax(x)
x[t]=0
x

[0.59800382 0.46119986 0.89339658 0.44446569 0.85765404 0.36080554
 0.73914812 0.07877692 0.1491583  0.01090131]


array([0.59800382, 0.46119986, 0.        , 0.44446569, 0.85765404,
       0.36080554, 0.73914812, 0.07877692, 0.1491583 , 0.01090131])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
z=np.zeros((5,5),[('x',float),('y',float)])
z['x'],z['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
x=np.arange(8)
y=x+0.5
c=1.0/np.subtract.outer(x,y)
print(np.linalg.det(c))


3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8,np.int32,np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=np.inf)
z=np.zeros((16,16))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
x = np.arange(100)
print("Original array:")
print(x)
a = np.random.uniform(0,100)
print("Value to compare:")
print(a)
index = (np.abs(x-a)).argmin()
print(x[index])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Value to compare:
89.69381334275468
90


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
a= np.random.random((10,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
d

array([[0.        , 0.65088354, 0.56708059, 0.78665829, 0.26682666,
        0.25075057, 0.5333185 , 0.19283986, 0.61905475, 0.65523458],
       [0.65088354, 0.        , 0.30810614, 0.26664995, 0.60656293,
        0.41156316, 0.23642659, 0.4750613 , 0.40360872, 0.17453456],
       [0.56708059, 0.30810614, 0.        , 0.2474056 , 0.40254571,
        0.33043848, 0.45122534, 0.37690606, 0.10389589, 0.16280633],
       [0.78665829, 0.26664995, 0.2474056 , 0.        , 0.64869642,
        0.53717694, 0.49662903, 0.59397914, 0.28002807, 0.13704874],
       [0.26682666, 0.60656293, 0.40254571, 0.64869642, 0.        ,
        0.23890916, 0.59055352, 0.19906875, 0.41603478, 0.53956572],
       [0.25075057, 0.41156316, 0.33043848, 0.53717694, 0.23890916,
        0.        , 0.353415  , 0.06350539, 0.40110296, 0.40465457],
       [0.5333185 , 0.23642659, 0.45122534, 0.49662903, 0.59055352,
        0.353415  , 0.        , 0.40656704, 0.55504111, 0.37960177],
       [0.19283986, 0.4750613 , 0.3769060

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
Z = np.arange(10, dtype=np.float32)
print(Z)
Z=Z.astype(np.int32, copy=False)
Z

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
Z = np.arange(9).reshape(3,3)
print(Z)
print("Using ndenumerate : \n", list(np.ndenumerate(Z)),'\n')
print("Using np.ndindex : \n")
l=[]
for index in np.ndindex(Z.shape):
    l.append((index, Z[index]))
print(l)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Using ndenumerate : 
 [((0, 0), 0), ((0, 1), 1), ((0, 2), 2), ((1, 0), 3), ((1, 1), 4), ((1, 2), 5), ((2, 0), 6), ((2, 1), 7), ((2, 2), 8)] 

Using np.ndindex : 

[((0, 0), 0), ((0, 1), 1), ((0, 2), 2), ((1, 0), 3), ((1, 1), 4), ((1, 2), 5), ((2, 0), 6), ((2, 1), 7), ((2, 2), 8)]


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))
t= np.random.choice(range(n*n), p, replace=False)
np.put(Z,t,[33,55,78])
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 78.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 55.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 33.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y

array([[-0.00144745,  0.19769394,  0.13829605,  0.29461939,  0.25566894,
        -0.02261543, -0.52698932, -0.33786951, -0.34313261,  0.34577601],
       [ 0.08167145,  0.14079056, -0.1483498 ,  0.42539087, -0.41181843,
        -0.18667643,  0.06238301, -0.15001255, -0.08673147,  0.27335277],
       [-0.28465307,  0.44882899, -0.50176729, -0.29353419,  0.06477744,
        -0.5231445 ,  0.39696361,  0.03993795,  0.30209075,  0.35050032],
       [ 0.14274422, -0.35173686, -0.3117306 ,  0.01925091,  0.20845628,
         0.13331469, -0.02280545,  0.33183095, -0.01246044, -0.13686368],
       [ 0.17619182,  0.0345026 , -0.3221784 ,  0.164369  ,  0.13832239,
        -0.55976102,  0.04516654,  0.12986459,  0.15720935,  0.03631313]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
A= np.random.randint(0,10,(3,3))
print(A,'\n')
print(A[:,1],"\n")
print(A[:,1].argsort(),"\n")
print(A[A[:,1].argsort()])

[[2 6 0]
 [9 7 2]
 [3 7 4]] 

[6 7 7] 

[0 1 2] 

[[2 6 0]
 [9 7 2]
 [3 7 4]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
Z = np.random.randint(0,3,(3,10))
print(Z,"\n")
print((~Z.any(axis=0)),"\n")
print((~Z.any(axis=0)).any())

[[2 1 2 0 0 1 0 2 2 2]
 [1 1 2 2 1 2 1 1 2 2]
 [1 2 0 0 2 0 2 2 1 1]] 

[False False False False False False False False False False] 

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5034889877518652


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "Array1")
print (Z)

[0 1 2 3 4 5 6 7 8 9]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),20)

np.add.at(Z, I, 1)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 3. 2. 5. 4. 1. 2. 4. 3. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[63 43 62 50]
 [49 33 48 67]
 [45 52 52 66]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)

S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)

D_counts = np.bincount(S)

D_means = D_sums / D_counts
print(D_means)

[0.63968438 0.41834491 0.41819733 0.38778382 0.4736395  0.70468701
 0.45016225 0.60947447 0.59853599 0.58661845]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.uniform(0,1,(4,4))
B = np.random.uniform(0,1,(4,4))

np.diag(np.dot(A, B))

array([1.30248663, 1.66721797, 0.36908556, 1.0980671 ])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
A = np.arange(25).reshape(5,5)
print(A,"\n")
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))

F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 58) ( 2, 65) ( 6, 16) ( 6, 53) ( 6, 82) ( 6, 97) (13, 53) (13, 78)
 (16, 97) (19, 32) (19, 41) (19, 86) (19, 89) (21, 47) (21, 66) (32, 89)
 (36, 83) (36, 84) (41, 86) (47, 66) (53, 78) (53, 82) (55, 66) (55, 85)
 (58, 65) (65, 71) (65, 99) (66, 85) (71, 99) (83, 84)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6]) 
print(C)
print(np.arange(len(C)),"\n")
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1]
[0 1 2 3 4 5 6] 

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
Z = np.random.randint(0,2,100)
print(Z,"\n")
print(np.logical_not(Z, out=Z))

Z = np.random.uniform(-1.0,1.0,100)
print(Z)
np.negative(Z, out=Z)

[0 0 1 1 0 0 1 1 0 1 1 1 0 1 0 1 0 0 0 1 1 0 1 0 1 1 1 0 1 0 0 0 0 0 1 0 0
 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 0 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1
 1 1 0 1 0 1 0 1 0 0 1 1 1 1 0 1 1 0 0 1 1 0 1 0 0 0] 

[1 1 0 0 1 1 0 0 1 0 0 0 1 0 1 0 1 1 1 0 0 1 0 1 0 0 0 1 0 1 1 1 1 1 0 1 1
 1 1 0 0 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0
 0 0 1 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 1 0 0 1 0 1 1 1]
[ 2.21771817e-01 -3.48004700e-01 -4.06930299e-01 -7.97943490e-01
  1.84942734e-01  1.75704865e-01  8.70350968e-01 -4.06262283e-02
 -8.12763371e-01 -6.35766606e-02 -3.63856489e-01  7.22963803e-01
 -5.71238151e-02  6.84707213e-01  4.30864606e-01 -8.50654588e-01
 -8.74217054e-01  8.83633805e-01 -4.66090474e-04 -2.75397212e-01
  4.57287380e-01 -5.76672438e-01 -9.53860799e-02 -9.58672786e-01
  9.88106578e-01  6.26851723e-01 -5.57859395e-01 -7.09151228e-01
 -7.29743558e-01 -7.61330401e-01  9.64587357e-02 -2.53746277e-02
  7.67123849e-01 -6.81337507e-01  3.35127734e-01 -4.29632909e-01
 -5.8

array([-2.21771817e-01,  3.48004700e-01,  4.06930299e-01,  7.97943490e-01,
       -1.84942734e-01, -1.75704865e-01, -8.70350968e-01,  4.06262283e-02,
        8.12763371e-01,  6.35766606e-02,  3.63856489e-01, -7.22963803e-01,
        5.71238151e-02, -6.84707213e-01, -4.30864606e-01,  8.50654588e-01,
        8.74217054e-01, -8.83633805e-01,  4.66090474e-04,  2.75397212e-01,
       -4.57287380e-01,  5.76672438e-01,  9.53860799e-02,  9.58672786e-01,
       -9.88106578e-01, -6.26851723e-01,  5.57859395e-01,  7.09151228e-01,
        7.29743558e-01,  7.61330401e-01, -9.64587357e-02,  2.53746277e-02,
       -7.67123849e-01,  6.81337507e-01, -3.35127734e-01,  4.29632909e-01,
        5.85037548e-01, -6.38097478e-01,  7.99380899e-01, -3.98387664e-01,
       -5.42541082e-01,  5.17633331e-01, -2.45499713e-01,  7.27685323e-01,
        6.25713314e-01,  5.66230188e-02,  8.24274974e-01, -7.87285683e-01,
       -8.81589537e-01,  9.19241185e-01, -9.38609902e-01, -2.21379974e-01,
        2.90025750e-01,  

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 5.20301065  7.23488126 11.23976614  5.58342603  9.98974396  3.82246681
  2.44363365 12.48666047  3.64863176  9.30697202]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[11.62473464  7.86529998  8.70614376 10.16402728 10.46819     3.17728237
   2.68415715  8.26410624 13.63585185  2.69088974]
 [ 5.889665    1.88022625  9.96571267  5.24900643  5.8563313   0.69005719
   3.51740534  2.62104062  8.73253999  5.79986389]
 [ 3.27746304  0.55357887 12.71421792  2.3481258   6.23917209  3.6995426
   5.68058618  2.13836623  8.90373257  8.79449765]
 [ 7.18806396  3.49250707 11.595011    5.778825    9.08659818  0.91310671
   1.53108136  5.73632926 11.95933788  6.485601  ]
 [ 3.38317548  0.96031546  8.84352549  3.61022093  1.93067495  1.42040738
   6.73654428  1.45086648  4.74018669  5.94452796]
 [12.33350734  6.99710199  3.41382623 14.41440468  2.62411995 10.52087315
   0.18854719  2.52320773  1.01360335  6.37754268]
 [ 2.98976492  2.33903663  1.72574491  5.46662912  6.61228194  2.44837979
   9.35321914  8.7533699   3.56140917  0.92868881]
 [ 7.91879735  2.78776722  0.51599123  9.7296007   2.79386341  5.84518227
   4.06195054  4.02552278  0.51211512  1.83566899]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[0 9 2 6 8 1 7 4 6 3]
 [2 1 8 9 7 3 4 9 5 5]
 [5 9 8 6 6 0 5 7 0 2]
 [6 3 7 5 8 2 7 6 0 4]
 [5 9 9 9 1 3 5 5 9 3]
 [5 1 7 5 4 5 6 8 6 1]
 [3 9 7 1 2 0 8 8 7 8]
 [4 4 6 8 1 8 0 0 5 7]
 [2 5 3 2 6 4 4 8 4 3]
 [1 0 9 9 7 3 4 5 2 5]]
[[0 0 0 0 0]
 [0 0 9 2 6]
 [0 2 1 8 9]
 [0 5 9 8 6]
 [0 6 3 7 5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
from numpy.lib import stride_tricks
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 3 1]
   [3 3 4]
   [1 1 0]]

  [[3 1 2]
   [3 4 0]
   [1 0 4]]

  [[1 2 2]
   [4 0 1]
   [0 4 3]]

  [[2 2 2]
   [0 1 0]
   [4 3 4]]

  [[2 2 2]
   [1 0 0]
   [3 4 1]]

  [[2 2 3]
   [0 0 1]
   [4 1 3]]

  [[2 3 4]
   [0 1 1]
   [1 3 4]]

  [[3 4 0]
   [1 1 4]
   [3 4 2]]]


 [[[3 3 4]
   [1 1 0]
   [3 2 2]]

  [[3 4 0]
   [1 0 4]
   [2 2 3]]

  [[4 0 1]
   [0 4 3]
   [2 3 0]]

  [[0 1 0]
   [4 3 4]
   [3 0 4]]

  [[1 0 0]
   [3 4 1]
   [0 4 3]]

  [[0 0 1]
   [4 1 3]
   [4 3 3]]

  [[0 1 1]
   [1 3 4]
   [3 3 1]]

  [[1 1 4]
   [3 4 2]
   [3 1 1]]]


 [[[1 1 0]
   [3 2 2]
   [3 3 0]]

  [[1 0 4]
   [2 2 3]
   [3 0 0]]

  [[0 4 3]
   [2 3 0]
   [0 0 1]]

  [[4 3 4]
   [3 0 4]
   [0 1 1]]

  [[3 4 1]
   [0 4 3]
   [1 1 0]]

  [[4 1 3]
   [4 3 3]
   [1 0 3]]

  [[1 3 4]
   [3 3 1]
   [0 3 4]]

  [[3 4 2]
   [3 1 1]
   [3 4 1]]]


 [[[3 2 2]
   [3 3 0]
   [0 2 2]]

  [[2 2 3]
   [3 0 0]
   [2 2 1]]

  [[2 3 0]
   [0 0 1]
   [2 1 4]]

  [[3 0 4]
   [0 1 1]
   [1 4 0]]

  [[0 4 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S

Symetric([[ 7, 12,  6,  7, 10],
          [12,  5,  7, 13, 11],
          [ 6,  7,  4,  6, 15],
          [ 7, 13,  6,  5,  7],
          [10, 11, 15,  7,  9]])

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 1 0 1 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1
  0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1
  0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9995 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
print(Z)
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]
[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

4.31 s ± 487 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
183 ms ± 13.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
168 ms ± 4.19 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 3 4]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 4 2]
 [0 3 1]
 [3 2 2]
 [1 4 4]
 [2 0 4]
 [0 0 1]
 [3 0 4]
 [4 4 1]
 [2 2 3]
 [1 3 2]]
[[3 4 2]
 [0 3 1]
 [3 2 2]
 [1 4 4]
 [2 0 4]
 [0 0 1]
 [3 0 4]
 [4 4 1]
 [2 2 3]
 [1 3 2]]
[[3 4 2]
 [0 3 1]
 [3 2 2]
 [1 4 4]
 [2 0 4]
 [0 0 1]
 [3 0 4]
 [4 4 1]
 [2 2 3]
 [1 3 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)      
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.02049542, 0.04177314, 0.03810238, 0.02025258, 0.00647106,
        0.00949864, 0.02308917, 0.00311886, 0.01524949, 0.02099736],
       [0.36401985, 0.74193415, 0.67673768, 0.35970679, 0.11493271,
        0.16870572, 0.41008761, 0.05539415, 0.27084679, 0.37293476],
       [0.17047624, 0.34745948, 0.31692694, 0.16845637, 0.0538248 ,
        0.07900755, 0.1920505 , 0.02594196, 0.12684183, 0.17465124],
       [0.31962641, 0.65145281, 0.59420727, 0.31583935, 0.10091629,
        0.14813149, 0.36007606, 0.04863865, 0.23781613, 0.32745413],
       [0.22639504, 0.46143147, 0.4208838 , 0.22371262, 0.07148016,
        0.10492323, 0.25504599, 0.03445131, 0.16844788, 0.2319395 ],
       [0.0204579 , 0.04169667, 0.03803263, 0.02021551, 0.00645921,
        0.00948125, 0.02304691, 0.00311315, 0.01522158, 0.02095892],
       [0.09416278, 0.1919197 , 0.17505502, 0.0930471 , 0.0297302 ,
        0.04363993, 0.10607935, 0.01432907, 0.07006125, 0.09646884],
       [0.31747778, 0.64707353, 0.5902128

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)               
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.06979742  0.32838813]
